feat: agent install name
dyrector-io/dyrectorio pull request #1016
Opened 2024-11-22 13:47 UTC by robot9706

Implemented the option to change the container name of dagent, to avoid name collision when installing multiple agents on the same node.

2024-11-22 14:25 UTC, nandor-magyar commented
The same collision is true for crane as well. The name `workload` would be more appropriate to address the running instances of both environments.

2024-11-25 09:31 UTC, m8vago commented on web/crux-ui/src/models/node.ts
> +  workloadName?: string
Please add it to the validation schema as well.

2024-11-25 09:32 UTC, m8vago commented on web/crux/assets/install-script/install-docker.ps1.hbr
> +  --name '{{#if workloadName}}{{workloadName}}{{else}}dagent{{/if}}' `
would be nicer imho, if we could refrain to use handlebar conditions and move this if to the ts side. so the template simply can be workloadName

2024-11-27 09:58 UTC, polaroi8d requested changes
Please implement a container name validation. 

After naming the agent to: `teszting 0001 ?#@$_+)!@31 `, got the following command after running the curl command: 
```
docker: Error response from daemon: Invalid container name (teszting 0001 ?#@$_+)!@31 ), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed.
```

2024-11-28 07:44 UTC, m8vago approved these changes

2024-11-28 17:59 UTC, polaroi8d approved these changes

2024-11-28 17:59 UTC, merged