feat(web): deployments list pagination & filtering
dyrector-io/dyrectorio pull request #1021
Opened 2024-11-27 14:54 UTC by robot9706

Add deployments list pagination & extra filtering for nodes.

Depends on #1018

2024-12-03 14:09 UTC, m8vago requested changes

2024-12-04 12:50 UTC, m8vago approved these changes
Wait with the merge for the config refactor

2024-12-04 13:43 UTC, robot9706 commented
Merged into `feat/release-candidate`

2025-01-06 17:32 UTC, m8vago approved these changes

2025-01-07 13:58 UTC, merged