feat(web): specify pipeline target branch
dyrector-io/dyrectorio pull request #1023
Opened 2024-12-03 11:37 UTC by robot9706

Add option to specify Azure pipeline target branch.

2024-12-03 14:00 UTC, m8vago commented on web/crux-ui/src/components/pipelines/edit-pipeline-card.tsx
> +    branch: null,
should be '' to avoid uncontrolled input errors

2024-12-03 14:02 UTC, m8vago requested changes

2024-12-03 14:02 UTC, m8vago commented on web/crux-ui/src/components/pipelines/edit-pipeline-card.tsx
> +    branch: null,
should be '' to avoid uncontrolled input errors

2024-12-04 12:51 UTC, m8vago approved these changes
Wait with the merge for the config rector

2024-12-04 13:42 UTC, robot9706 commented
Merged into `feat/release-candidate`

2025-01-08 10:48 UTC, merged