Feat(crux-ui): improve profile page
dyrector-io/dyrectorio pull request #113
Opened 2022-08-24 14:59 UTC by bvektor

2022-08-24 15:34 UTC, polaroi8d approved these changes
LGTM (informal)

2022-08-25 08:30 UTC, robot9706 requested changes

2022-08-25 08:30 UTC, robot9706 commented on web/crux-ui/src/pages/api/auth/settings/edit-profile.ts
> +    return
Changing password *and* email/name at the same time is not possible this way. 😏

2022-08-25 13:37 UTC, robot9706 approved these changes
😎

2022-08-25 13:38 UTC, merged