Feat/add traefik to cli
dyrector-io/dyrectorio pull request #248
Opened 2022-10-07 14:32 UTC by c3ppc3pp

2022-10-10 07:09 UTC, robot9706 requested changes
Comment + testing in progress 🏗

2022-10-10 07:09 UTC, robot9706 commented on cli/container_defaults.go
> +		// WithEnv([]string{
Comments 🙀

2022-10-10 09:21 UTC, c3ppc3pp commented on cli/container_defaults.go
> +		// WithEnv([]string{
done, thanks!

2022-10-10 09:29 UTC, c3ppc3pp commented on cli/runner.go
> +		log.Fatalf("error: %v", err)
Added more verbosity, in this case the underlying docker SDK should provide proper error message.

2022-10-10 09:29 UTC, c3ppc3pp commented on cli/runner.go
> +		log.Fatalf("error: %v", err)
Added more verbosity, in this case the underlying docker SDK should provide proper error message as the dagentutils package doesn't provide its own error messages.

2022-10-10 14:17 UTC, polaroi8d approved these changes
LGTM (informal), tested in local and works like a charm 🦄

2022-10-10 21:44 UTC, c3ppc3pp commented on cli/runner.go
> +		log.Fatalf("error: %v", err)
We talked about this earlier, I redid the formatting, should report errors like you described.

2022-10-11 07:13 UTC, nandor-magyar commented on cli/main.go
> +const errmsg = "%s: %v"
This doesn't make the code more readable, rather the opposite.

2022-10-11 10:02 UTC, nandor-magyar commented
Please rebase.

2022-10-11 11:24 UTC, robot9706 approved these changes
🚀

2022-10-11 11:24 UTC, merged