feat(crux-ui): editor highlighting
dyrector-io/dyrectorio pull request #260
Opened 2022-10-11 10:16 UTC by m8vago

feat: add editor input highlighting to version image editing and deployment editing.
feat: add editors list to relevant pages
feat: add focus based saving
fix: a couple of websocket related errors
refactor: add useRepatch() and replace useReducer() in some components
refactor: state handling in websocket edited pages

2022-10-13 14:02 UTC, robot9706 requested changes
Minor typo otherwise LGTM 😎

2022-10-14 07:23 UTC, balanceee approved these changes
+1

2022-10-14 07:38 UTC, peterambrus3 commented on web/crux-ui/src/components/editor/multi-input.tsx
> +  const { id, disabled, editorOptions, style: propsStyle, value, onPatch, ...forwaredProps } = props
typo forwardedProps ?

2022-10-14 07:56 UTC, peterambrus3 requested changes
comment, otherwise lgtm

2022-10-14 09:41 UTC, m8vago commented on web/crux-ui/src/components/editor/multi-input.tsx
> +  const { id, disabled, editorOptions, style: propsStyle, value, onPatch, ...forwaredProps } = props
yap, ty!

2022-10-14 10:42 UTC, robot9706 approved these changes
LGTM 😎

2022-10-14 10:44 UTC, peterambrus3 approved these changes

2022-10-14 10:45 UTC, merged