test: add some unit tests for dagent
dyrector-io/dyrectorio pull request #263
Opened 2022-10-13 20:58 UTC by Fall1ngStar

Add unit tests in `dagent` package to increase code coverage (#241)

2022-10-13 21:06 UTC, Fall1ngStar commented
I've added unit tests to as much pure functions as I could, if you have any tips on how to add tests for functions that interact with other components, I'll be glad to add more tests

2022-10-14 06:34 UTC, nandor-magyar requested changes

2022-10-14 06:34 UTC, nandor-magyar commented on agent/pkg/dagent/caps/parser_test.go
> +	a := map[string]string{
Please use more meaningful names, like `a: labels`, `b: config`.

2022-10-14 06:34 UTC, nandor-magyar commented on agent/pkg/dagent/utils/import_container_test.go
> +	ml := []mount.Mount{
ml? More verbose name please.

2022-10-18 14:22 UTC, polaroi8d approved these changes
LGTM (informal) thanks anyway good job. Could you please sign your commits?

2022-10-18 14:23 UTC, Fall1ngStar commented
Will do !

2022-10-20 08:45 UTC, nandor-magyar approved these changes
:+1:

2022-10-20 08:46 UTC, merged