refactor(test): add unit test for crane clients
dyrector-io/dyrectorio pull request #268
Opened 2022-10-16 01:03 UTC by SilverTux

This PR also aims to achieve https://github.com/dyrector-io/dyrectorio/issues/241 goals testing crane/k8s/clients.go

2022-10-17 06:41 UTC, nandor-magyar requested changes

2022-10-17 10:19 UTC, SilverTux commented on agent/pkg/crane/k8s/clients.go
> +	InClusterConfig      = rest.InClusterConfig
I've chosen to make a new type where the dependent functions are fields of the struct so I can get rid of using globals, and relatively easy to replace those in unit tests. What do you think about this solution?

2022-10-18 14:20 UTC, polaroi8d approved these changes
LGTM (informal) anyway good job, thanks! ✋🏻

2022-10-20 09:29 UTC, nandor-magyar commented on agent/pkg/crane/k8s/clients.go
> +	InClusterConfig      = rest.InClusterConfig
This also looks a bit wonky. The struct has the functions with the same header and a slightly different behavior. However, I don't have any significantly better idea, so still good job :+1:

2022-10-20 09:32 UTC, nandor-magyar requested changes

2022-10-20 11:07 UTC, SilverTux commented on agent/pkg/crane/k8s/clients_test.go
> +	assert.NotEqual(t, nil, resultClient)
You are right using that is more elegant, thank you! I've fixed those :)

2022-10-20 11:14 UTC, m8vago approved these changes

2022-10-20 11:22 UTC, nandor-magyar approved these changes

2022-10-20 11:46 UTC, merged