test(crux-ui): add e2e tests to node screen
dyrector-io/dyrectorio pull request #331
Opened 2022-11-11 13:55 UTC by balanceee

2022-11-11 14:01 UTC, polaroi8d commented on web/crux-ui/e2e/nodes.spec.ts
> +test('Install dagent should be successful', async ({ page }) => {
Wow!!! 🔥

2022-11-11 14:01 UTC, polaroi8d approved these changes
Awesome job, small quesiton but looks good to me.

2022-11-11 14:02 UTC, polaroi8d commented on web/crux-ui/e2e/nodes.spec.ts
> +      : null
What if I run the test in MacOS or on the Github Actions?

2022-11-14 07:29 UTC, robot9706 requested changes

2022-11-14 07:29 UTC, robot9706 commented on web/crux-ui/e2e/nodes.spec.ts
> +  exec(curl, settings, (err, stdout, stderr) => {
I think the test should remove the dagent container after the test is finished.

2022-11-15 13:28 UTC, robot9706 approved these changes

2022-11-15 13:28 UTC, merged