fix(crux): move platform detection after priviledge escalation in install.docker.hbr
dyrector-io/dyrectorio pull request #348
Opened 2022-11-16 14:53 UTC by m8vago

2022-11-16 14:55 UTC, polaroi8d commented on web/crux/install-docker.sh.hbr
> +      if [ ${DOCKER_HOST:0:7} == "unix://" ]; then
🦅

2022-11-16 15:00 UTC, polaroi8d approved these changes
LGTM works on MacOS

2022-11-16 15:14 UTC, c3ppc3pp approved these changes

2022-11-17 10:13 UTC, balanceee requested changes
Not working on windows:
Installation process needs root privileges

2022-11-17 12:01 UTC, m8vago commented
> Not working on windows: Installation process needs root privileges

Thanks! Fixed and tested on @robot9706 's machine

2022-11-17 12:21 UTC, balanceee approved these changes

2022-11-17 12:21 UTC, merged