fix(cli): crux agent address env var
dyrector-io/dyrectorio pull request #353
Opened 2022-11-18 11:46 UTC by c3ppc3pp

2022-11-19 12:04 UTC, m8vago commented on golang/pkg/cli/container_defaults.go
> +			fmt.Sprintf("CRUX_UI_URL=%s:%d", "localhost", settings.SettingsFile.TraefikWebPort),
it looks less readable for me

2022-11-19 12:05 UTC, m8vago approved these changes

2022-11-21 11:13 UTC, c3ppc3pp commented on golang/pkg/cli/container_defaults.go
> +			fmt.Sprintf("CRUX_UI_URL=%s:%d", "localhost", settings.SettingsFile.TraefikWebPort),
fixed, thanks

2022-11-21 11:45 UTC, robot9706 requested changes

2022-11-21 11:45 UTC, robot9706 commented on golang/pkg/cli/container_defaults.go
> +		//		WithLogWriter(nil).
Comment line :o

2022-11-21 12:00 UTC, c3ppc3pp commented on golang/pkg/cli/container_defaults.go
> +		//		WithLogWriter(nil).
Nice catch! Reverted.

2022-11-21 12:23 UTC, robot9706 approved these changes
LGTM 🦥

2022-11-21 15:09 UTC, merged