feat(web): add dashboard
dyrector-io/dyrectorio pull request #396
Opened 2022-12-12 14:51 UTC by balanceee

2022-12-12 15:09 UTC, peterambrus3 commented on protobuf/proto/crux.proto
> +
remove newline

2022-12-12 15:09 UTC, peterambrus3 commented on protobuf/proto/crux.proto
> +}
no newline

2022-12-12 17:40 UTC, polaroi8d commented on web/crux-ui/e2e/utils/global-setup.ts
> +import { ROUTE_LOGIN, ROUTE_TEAMS_CREATE, verificationUrl } from '@app/routes'
What's the difference between lines 1 and 3?

2022-12-12 19:19 UTC, polaroi8d commented on web/crux/src/app/dashboard/dashboard.service.ts
> +      where: {
It can't be replaced with `teamFilter`?

2022-12-13 07:58 UTC, robot9706 requested changes
Minor comment, also testing in progress. 🚀

2022-12-13 07:58 UTC, robot9706 commented on protobuf/proto/crux.proto
> +  uint32 products = 103;
102 missing?

2022-12-13 13:16 UTC, robot9706 approved these changes
LGTM, tested 🚀

2022-12-14 07:46 UTC, peterambrus3 approved these changes

2022-12-14 08:00 UTC, merged