feat(crux): reworked email and notification templating
dyrector-io/dyrectorio pull request #454
Opened 2023-02-06 14:54 UTC by robot9706

- Removed hardcoded notification and email texts from code and moved them to template files
- Implemented a simple template file
- Moved email and chat templates to a new `assets` folder
- Moved the install scripts from the root folder to the `assets` folder as well

❓`assets` folder, template format (inplace + hbr file), `notification.template.builder.ts` service (naming?)

2023-02-10 11:24 UTC, m8vago commented on web/crux-ui/src/components/nodes/dyo-node-setup.tsx
> +              if (it === 'k8s') {
we should move this if to the onTypeChanged callback, if that's possible

2023-02-10 11:27 UTC, m8vago commented on web/crux/src/builders/notification.template.builder.ts
> +  private processTemplateEntry<TData>(entry: TemplateEntry, data: TData): string {
simply use T or TemplateType, please

2023-02-13 10:50 UTC, polaroi8d requested changes

2023-02-13 11:00 UTC, polaroi8d commented on web/crux/src/builders/notification.template.builder.ts
> +    return Handlebars.compile(templateText)(data)
"I am not very familiar with Handlebars, but what if it throws an exception? Isn't it necessary to have:

```
    try {
      return Handlebars.compile(templateText)(data);
    } catch (error) {
      throw new Error(`Could not compile template: ${error.message}`);
    }
    ```

2023-02-13 12:29 UTC, robot9706 commented on web/crux/assets/chat/invite.json
> +{
Works for me (`notificationTemaple` 😉 ).

2023-02-13 12:29 UTC, m8vago approved these changes

2023-02-13 14:30 UTC, polaroi8d approved these changes
LGTM

2023-02-13 14:35 UTC, merged