refactor(crux): refactor email service
dyrector-io/dyrectorio pull request #50
Opened 2022-07-27 12:50 UTC by balanceee

2022-07-27 14:59 UTC, polaroi8d requested changes

2022-07-27 14:59 UTC, polaroi8d commented on web/crux/src/services/email-builder.service.ts
> +      sender: sender,
I think we can stick with the SendGrid.MailDataRequired properties. (instead of sender and recipient use, from and to)

2022-07-27 14:59 UTC, polaroi8d commented on web/crux/src/services/email-builder.service.ts
> +      sender: sender,
After you don't need to implement a custom `EmailItem` we can use the SendGrid.MailData type. (for now its more readable than add some extra type)

2022-07-27 14:59 UTC, polaroi8d commented on web/crux/src/services/email-builder.service.ts
> +    const button = teamId ? 'Accept' : 'Create account'
It would be better if we check `teamId` only once and create a full object based on the output.

2022-07-27 14:59 UTC, polaroi8d commented on web/crux/src/services/email.service.ts
> +    } catch (ex) {
User err or error please.

2022-07-27 14:59 UTC, polaroi8d commented on web/crux/src/services/email.service.ts
> +    SendGrid.setApiKey(SENDGRID_KEY)
What if the SENDGRID_KEY is invalid?

2022-07-27 14:59 UTC, polaroi8d commented on web/crux/src/services/email-builder.service.ts
> +import { Injectable } from '@nestjs/common'
Create a builder/ folder for this EmailBuilder.

2022-07-27 14:59 UTC, polaroi8d commented on web/crux/src/services/email-builder.service.ts
> +      return null
Return with exception.

2022-07-28 06:56 UTC, balanceee commented on web/crux/src/services/email.service.ts
> +    SendGrid.setApiKey(SENDGRID_KEY)
EmailService will handle that case.

2022-07-28 09:28 UTC, polaroi8d requested changes

2022-07-28 09:28 UTC, polaroi8d commented on web/crux/src/builders/email-builder.ts
> +import { Injectable } from '@nestjs/common'
Prettier formatting erros & rename the file to `email.builder.ts` pls.

2022-07-28 09:57 UTC, polaroi8d approved these changes
LGTM

2022-07-28 09:59 UTC, robot9706 approved these changes
😎

2022-07-28 09:59 UTC, merged

2022-07-28 10:01 UTC, balanceee reviewed
LGTM