feat(web): refactor gRPC to HTTP API
dyrector-io/dyrectorio pull request #506
Opened 2023-03-20 12:02 UTC by robot9706

Refactored the following gRPC (`crux` and `crux-ui`) APIs to REST:

- Audit
- Dashboard
- Product
- Registry
- Token
- Version

Co-authored-by: Mate Vago < @m8vago >
Co-authored-by: Levente Orban < @polaroi8d >

2023-03-20 12:25 UTC, polaroi8d commented on web/crux/src/app/product/product.dto.ts
> +  description?: string | undefined
Why we need undefined?

2023-03-20 14:00 UTC, m8vago requested changes

2023-03-21 10:43 UTC, m8vago commented on web/crux-ui/src/models/audit.ts
> +  updatedAt?: string | null
this will never be null

2023-03-21 10:48 UTC, m8vago commented on web/crux-ui/src/routes.ts
> +export const registryApiUrl = (id: string) => `/api/new${registryUrl(id)}`
`${API_REGISTRIES}/${id}`

2023-03-21 10:52 UTC, m8vago commented on web/crux/src/app/registry/registry.dto.ts
> +const RegistryDetailOneOf = () =>
Details*

2023-03-21 10:53 UTC, m8vago commented on web/crux/src/app/registry/registry.http.controller.ts
> +  @AuditLogLevel('disabled')
unnecessary

2023-03-21 10:57 UTC, m8vago commented on web/crux/src/app/token/token.http.controller.ts
> +  @ApiCreatedResponse({
create a custom decorator for this like the @TokenId up there

2023-03-21 10:57 UTC, m8vago commented on web/crux/src/app/token/token.mapper.ts
> +  listItemToDto(token: PrismaToken): Token {
toDto

2023-03-21 10:58 UTC, m8vago commented on web/crux/src/app/token/token.mapper.ts
> +  generateResponseToDto(prismaToken: PrismaToken, jwt: string) {
missing return type

2023-03-21 11:09 UTC, m8vago commented on web/crux/src/app/version/version.mapper.ts
> +        config: it.config as any as ContainerConfigData,
replace this with ContainerConfigDto

2023-03-21 14:59 UTC, m8vago approved these changes

2023-03-21 16:17 UTC, polaroi8d approved these changes

2023-03-21 16:27 UTC, merged