refactor(agent): tests
dyrector-io/dyrectorio pull request #54
Opened 2022-07-29 10:37 UTC by robot9706

2022-07-29 13:50 UTC, polaroi8d approved these changes

2022-07-31 17:23 UTC, nandor-magyar requested changes
In general, i think the test cases should have this structure:
1. prepare
2. act - use the functions at matter
3. assert - validate results
4. cleanup, if need be

The type is nice that you have created for testing, The AssertFn could return a `func(expected string)` error, that is executed at the end of the the test function.
A good assert communicates the behavior and the expectations clearly.

2022-07-31 17:23 UTC, nandor-magyar commented on agent/internal/dogger/dogger_test.go
> +func TestDoggerErrorTest(t *testing.T) {
No assertion in test case.

2022-07-31 17:23 UTC, nandor-magyar commented on agent/internal/dogger/dogger_test.go
> +			return errors.New("Test error")
missing assertion

2022-08-01 10:52 UTC, nandor-magyar approved these changes

2022-08-01 10:58 UTC, merged