refactor(agent): gRPC communication with core
dyrector-io/dyrectorio pull request #61
Opened 2022-08-03 12:44 UTC by robot9706

2022-08-04 10:44 UTC, nandor-magyar commented
Please remove the unnecessary masrhal / unmarshal test functions.

2022-08-04 10:57 UTC, nandor-magyar commented on agent/internal/grpc/grpc.go
> +		var versionData *v1.VersionData = nil
default is nil for pointers, it is unnecessary to explicitly declare.

2022-08-04 10:57 UTC, nandor-magyar commented on protobuf/proto/agent.proto
> +    DeployRequestCore deployCore = 4;
Use of the word Legacy instead of Core? What do you think? Core might not say anything to the reader.

2022-08-04 11:52 UTC, nandor-magyar approved these changes

2022-08-05 12:09 UTC, m8vago requested changes
prename to prefix

2022-08-08 09:00 UTC, m8vago approved these changes

2022-08-08 09:09 UTC, merged