Feat/agent package version
dyrector-io/dyrectorio pull request #622
Opened 2023-05-17 13:37 UTC by robot9706

- When changing teams the browser does not correctly reload showing the old team
- Crux uses an environment variable for agent installation, replaced with major + minor from package version
- When an agent connects the version is matched against crux to make sure it is compatible (only in PRODUCTION mode)

2023-05-17 13:40 UTC, robot9706 commented
Should I use 'latest' in non production mode so development is easier or everybody should just set `CRUX_AGENT_IMAGE` in their .envs?

2023-05-18 06:07 UTC, polaroi8d requested changes
I'm missing the unit tests for `getAgentVersionFromPackage` and `agentVersionSupported`.

2023-05-18 11:31 UTC, polaroi8d approved these changes

2023-05-18 12:00 UTC, m8vago commented on web/crux/src/shared/package.ts
> +const pkg = require('../../package.json')
Use `const version = this.configService.get<string>('npm_package_version')`

2023-05-18 12:03 UTC, polaroi8d commented on web/crux/src/app/agent/agent.service.spec.ts
> +    it('handleConnect should close connection if an agent has a non supported version', async () => {
Hmm good case, I think If you update the instance and the agent tries to connect with the wrong version, we should easily just kick them. (After that you have to update agents as well, to workaround your problem)

2023-05-18 12:08 UTC, m8vago commented on web/crux/src/app/agent/agent.service.spec.ts
> +    it('handleConnect should close connection if an agent has a non supported version', async () => {
But we have the node update feature and if we kick them immediately the users can not update their agent without revoking the token.

2023-05-18 12:18 UTC, polaroi8d commented on web/crux/src/app/agent/agent.service.spec.ts
> +    it('handleConnect should close connection if an agent has a non supported version', async () => {
Then what, If we automatically update the agents if the platform version is bumped?

2023-05-18 13:13 UTC, m8vago commented on web/crux/src/app/agent/agent.service.spec.ts
> +    it('handleConnect should close connection if an agent has a non supported version', async () => {
Conclusion: We will try to update once.
If it failes we shut down the agent. 
The ultimate solution will be developed in a different PR.

2023-05-22 14:23 UTC, m8vago approved these changes

2023-05-22 14:23 UTC, merged