ci: add on-push restarts
dyrector-io/dyrectorio pull request #649
Opened 2023-05-25 21:43 UTC by nandor-magyar

2023-05-30 10:27 UTC, polaroi8d requested changes

2023-05-30 10:27 UTC, polaroi8d commented on .github/workflows/full.yml
> +  crux_test_deploy:
Not proper naming: `crux_test_deploy`

2023-05-30 10:27 UTC, polaroi8d commented on .github/workflows/full.yml
> +    # needs: [crux_push]
Unnecessary comment.

2023-05-31 09:34 UTC, nandor-magyar commented on .github/workflows/full.yml
> +    # needs: [crux_push]
It will be uncommented if ready.

2023-05-31 09:35 UTC, polaroi8d commented on .github/workflows/full.yml
> +    # needs: [crux_push]
Okay, it was not draft :')

2023-06-07 14:08 UTC, nandor-magyar commented
Set to be done later, AD and GitHub is not willing to cooperate using their docs, contacting support.

2023-06-07 14:08 UTC, closed without merging