fix: web socket reconnect throttle
dyrector-io/dyrectorio pull request #675
Opened 2023-06-09 10:20 UTC by robot9706

When the WebSocket disconnects (due to an invalid or expired token) it tries to reconnect multiple times per second.
Implemented throttling to prevent this.

2023-06-09 13:14 UTC, polaroi8d approved these changes
You could add (web) scope to the pull request. Minor reviews, otherwise okay for me.

2023-06-09 13:14 UTC, polaroi8d commented on web/crux/src/websockets/dyo.ws.adapter.ts
> -      /* empty */
Thanks for deleted the empty catch.

2023-06-09 13:14 UTC, polaroi8d commented on web/crux-ui/src/websockets/websocket-client.ts
> +        this.logger.debug('Connecting...')
Who? to who? Can we add a little bit more verbose log message here?

2023-06-09 13:14 UTC, polaroi8d commented on web/crux-ui/src/websockets/websocket-client.ts
> +          this.logger.info('Connected')
Can we improve the same here?

2023-06-13 09:10 UTC, m8vago requested changes

2023-06-13 10:31 UTC, m8vago approved these changes

2023-06-13 10:31 UTC, merged