feat(crux-ui): playwright project
dyrector-io/dyrectorio pull request #691
Opened 2023-06-15 12:03 UTC by robot9706

- Rearranged playwright tests into projects which depend on eachother, so unecessary tests won't run.
- Adjusted `maxFailures` so 1 failure terminates testing.

2023-06-15 12:08 UTC, polaroi8d commented on web/crux-ui/e2e/utils/global.teardown.spec.ts
> +test('global teardown', async () => {
What is the test here?

2023-06-15 12:09 UTC, polaroi8d commented on web/crux-ui/package.json
> +    "test:e2e-debug": "DEBUG=1 playwright test --debug",
<3

2023-06-15 12:11 UTC, polaroi8d approved these changes
Small adjustments are okay for me, but please wait for @m8vago's review.

2023-06-15 12:12 UTC, robot9706 commented on web/crux-ui/e2e/with-login/nodes-deploy.spec.ts
> +const prefix = 'first'
Copied these from other test files, but yes we should use uppercase consts.

2023-06-15 18:04 UTC, m8vago requested changes

2023-06-16 08:37 UTC, robot9706 commented on web/crux-ui/playwright.config.ts
> +    createProject('test-registry', 'with-login/registry.spec.ts'),
Not really :)

2023-06-16 13:49 UTC, merged