feat(crux-ui): deployment table sorting
dyrector-io/dyrectorio pull request #704
Opened 2023-06-21 10:15 UTC by robot9706

Implemented a sorting hook to sort the deployment table in a version.

2023-06-26 11:04 UTC, m8vago requested changes

2023-06-26 11:45 UTC, robot9706 commented on web/crux-ui/src/components/projects/versions/version-deployments-section.tsx
> +              headerBuilder={sortHeaderBuilder<DeploymentByVersion, DeploymentSorting>(sorting, sortHeaders)}
Moved header translation to `sortHeaderBuilder`, this way it knows the column. What do you think?

2023-06-29 10:15 UTC, m8vago approved these changes

2023-06-29 10:18 UTC, m8vago commented on web/crux-ui/src/components/projects/versions/version-deployments-section.tsx
> +              headerBuilder={sortHeaderBuilder<DeploymentByVersion, DeploymentSorting>(sorting, sortHeaders)}
LGTM. Thank you!

2023-06-29 10:18 UTC, merged