feat: use docker events to track container states in dagent
dyrector-io/dyrectorio pull request #718
Opened 2023-06-27 13:37 UTC by robot9706

Instead of polling containers use docker events to only track changes and notify crux if something happened.

2023-06-29 10:49 UTC, nandor-magyar requested changes

2023-06-29 10:49 UTC, nandor-magyar commented on golang/pkg/dagent/utils/dockerhelper.go
> +	cli, err := client.NewClientWithOpts(client.FromEnv, client.WithAPIVersionNegotiation())
This is better as a parameter. You might need to split this into two because of this.

2023-06-29 10:49 UTC, nandor-magyar commented on golang/pkg/dagent/utils/dockerhelper.go
> +		destroy := &common.ContainerStateItem{
Since you are returning this right away, you could inline it into the return.

2023-06-29 10:53 UTC, m8vago requested changes

2023-06-29 10:53 UTC, m8vago commented on golang/internal/mapper/grpc.go
> +func MapContainerStates(in []dockerTypes.Container, prefix string) []*common.ContainerStateItem {
`MapContainerStateList` so we're not going to confuse it with `MapContainerState`

2023-06-29 10:53 UTC, m8vago commented on golang/pkg/crane/crux/deploy.go
> +	// TODO: Proper kubernetes event handling
Let's check if we can use kube's event api with the current .proto changes in the future.

2023-06-29 10:53 UTC, m8vago commented on golang/pkg/dagent/utils/dockerhelper.go
> +func eventToMessage(ctx context.Context, prefix string, event *events.Message) (*common.ContainerStateItem, error) {
Please rename it to something, which contain the actual struct names.

2023-06-29 10:53 UTC, m8vago commented on golang/pkg/dagent/utils/dockerhelper.go
> +		return nil, nil
Let's write a comment about why we ignore some events, and provide some examples.

2023-06-29 10:53 UTC, m8vago commented on web/crux/src/domain/container-status-watcher.ts
> +type StateMap = { [containerIdentifier: string]: ContainerStateItem }
`Record<string, ContainerStateItem>`

2023-06-29 10:53 UTC, m8vago commented on web/crux/src/domain/container-status-watcher.ts
> +        [Agent.containerPrefixNameOf(it.id)]: it,
Let's try to evade of creating new objects.

2023-07-05 11:05 UTC, m8vago approved these changes

2023-07-05 11:25 UTC, nandor-magyar approved these changes

2023-07-05 12:58 UTC, merged