fix: none container logger & port validation & moved in use warnings
dyrector-io/dyrectorio pull request #741
Opened 2023-07-11 13:14 UTC by robot9706

- Fixed an issue with dagent trying to find a 'none' logger driver
- Fixed an issue in dagent crashing if it failed to create a container
- Added validation to ports and port ranges overlapping
- Moved registry and storage in use warnings under the card title
- Fixed an issue with config JSON editors not sending patches due to an error in `mergeKeyValuesWithJson`

2023-07-11 14:09 UTC, polaroi8d commented on web/crux/src/app/deploy/deploy.mapper.ts
>        networks: this.mapUniqueKeyToStringArray(config.networks),
Don't we have a mapper test for this?

2023-07-11 14:13 UTC, robot9706 commented on web/crux/src/app/deploy/deploy.mapper.ts
>        networks: this.mapUniqueKeyToStringArray(config.networks),
I don't think so.

2023-07-13 12:16 UTC, polaroi8d commented on web/crux/src/app/deploy/deploy.mapper.spec.ts
> +  describe('dagentConfigToAgentProto logConfig', () => {
Nice 🥇

2023-07-13 12:16 UTC, polaroi8d approved these changes
LGTM (informal)

2023-07-14 06:56 UTC, ngyradi commented
Ports overlap empty port ranges, after deleting port ranges it still says overlapping unless the reset button has been used.

2023-07-14 09:27 UTC, ngyradi commented
works, tested locally

2023-07-14 09:31 UTC, m8vago requested changes

2023-07-14 09:31 UTC, m8vago commented on web/crux-ui/src/components/registries/edit-registry-card.tsx
> +        <DyoLabel className="mt-2 block" textColor="text-sm text-warning-orange">
We have `DyoMessage` for this purposes.

2023-07-14 09:31 UTC, m8vago commented on web/crux-ui/src/components/storages/edit-storage-card.tsx
> +        <DyoLabel className="mt-2" textColor="text-sm text-warning-orange">
same as above

2023-07-14 09:31 UTC, m8vago commented on web/crux-ui/src/validations/container.ts
> +    portRanges.length > 0 ? !portRanges.some(it => value >= it[field].from && value <= it[field].to) : true,
Please make a body for the lambda and declare some const to make this more readable.

2023-07-14 12:53 UTC, m8vago approved these changes

2023-07-14 13:19 UTC, merged