fix: improve release makefile command and update modules  @polaroi8d
dyrector-io/dyrectorio pull request #755
Opened 2023-07-19 12:06 UTC by polaroi8d

- Implement a simple function to enhance readability and replace new versions in the target JSON files when releasing a new function
- Fix a portion of the audit issues; some of them are still a work in progress

2023-07-19 12:26 UTC, nandor-magyar requested changes

2023-07-19 12:26 UTC, nandor-magyar commented on Makefile
> + Generate agent gRPC files
Zero #? :D

2023-07-19 17:25 UTC, polaroi8d commented on Makefile
> + Generate agent gRPC files
Fixed @nandor-magyar

2023-07-19 22:57 UTC, m8vago approved these changes

2023-07-20 10:24 UTC, nandor-magyar approved these changes

2023-07-20 11:23 UTC, merged