feat(crux, crux-ui): add notifications
dyrector-io/dyrectorio pull request #80
Opened 2022-08-12 08:02 UTC by balanceee

2022-08-12 08:23 UTC, peterambrus3 commented on web/crux-ui/locales/en/notifications.json
> +}
new line

2022-08-12 08:42 UTC, peterambrus3 commented on web/crux-ui/src/routes.ts
> +export const notificationApiHookUrl = () => `/api${ROUTE_NOTIFICATIONS}/hook`
new line

2022-08-12 08:58 UTC, peterambrus3 commented on web/crux/src/app/deploy/deploy.service.ts
> +        versionName: deployment.version.name,
version name duplicated in that deploy object

2022-08-12 09:28 UTC, robot9706 requested changes

2022-08-12 09:28 UTC, robot9706 commented on web/crux-ui/locales/en/notifications.json
> +    "teams": "MS Teams"
Why not use the full name `Microsoft Teams?`

2022-08-12 09:28 UTC, robot9706 commented on web/crux/src/app/agent/agent.service.ts
> +          deployment.status() == DeploymentStatus.SUCCESSFUL ? 'successfullDeploy' : 'failedDeploy'
`successfulDeploy` not `full` 🤔

2022-08-12 09:28 UTC, robot9706 commented on web/crux/src/app/deploy/deploy.controller.ts
> +import { concatAll, from, last, Observable } from 'rxjs'
Is `last` even used?

2022-08-12 09:28 UTC, robot9706 commented on web/crux/src/app/notification/notification.service.ts
> +      return {
Log error to see what's the problem later?

2022-08-12 09:56 UTC, robot9706 approved these changes
😎

2022-08-12 10:05 UTC, m8vago commented on web/crux-ui/locales/en/common.json
> +  "createdBy" : "Created by {{name}}",
createdByName

2022-08-12 10:10 UTC, m8vago commented on web/crux-ui/locales/en/notifications.json
> +  "title": "Notifications",
`title` is available as `common:notifications`
`title-notification` should be like:
`"notificationsName": "Notifications - {{name}}",`

2022-08-12 10:10 UTC, m8vago commented on web/crux-ui/locales/en/notifications.json
> +  "hook": {
noice

2022-08-12 10:11 UTC, m8vago commented on web/crux-ui/locales/en/notifications.json
> +    "common": "Get notifications via your hooks"
there gonna be more later on?

2022-08-12 10:13 UTC, m8vago commented on web/crux-ui/src/components/notifications/edit-notification-card.tsx
> +        : sendForm('POST', notificationApiUrl(), request as CreateNotification))
ROUTES_NOTIFICATIONS

2022-08-12 10:15 UTC, m8vago commented on web/crux-ui/src/components/notifications/edit-notification-card.tsx
> +  const [testDisabled, setTestDisabled] = useState<boolean>(true)
move this up to the other usestates pls.
Also the <boolean> is unnecessary, cause ts can infer it from the initial value

2022-08-12 10:16 UTC, m8vago commented on web/crux-ui/src/components/notifications/edit-notification-card.tsx
> +    setTestDisabled(formik.errors.url != undefined || formik.values.url.length == 0)
`!formik.errors.url` instead of != undefined

2022-08-12 10:16 UTC, m8vago commented on web/crux-ui/src/components/notifications/edit-notification-card.tsx
> +    const res = await fetch(notificationApiHookUrl(), {
this should be a constant

2022-08-12 10:17 UTC, m8vago commented on web/crux-ui/src/components/notifications/edit-notification-card.tsx
> +      const valid = (await res.json()) as boolean
the api should send respond with a 204 when success and with an error when not, so you need only check for res.ok

2022-08-12 10:18 UTC, m8vago commented on web/crux-ui/src/components/notifications/edit-notification-card.tsx
> +    <>
no need for this frame

2022-08-12 10:19 UTC, m8vago commented on web/crux-ui/locales/en/notifications.json
> +    "button": "Text Webhook",
should be text instead off button.
We should use keys which are descriptive.

2022-08-12 10:33 UTC, m8vago commented on web/crux-ui/src/components/notifications/notification-card.tsx
> +  const getDefaultImage = () => {
no need for this lambda

2022-08-12 10:34 UTC, m8vago commented on web/crux-ui/locales/en/common.json
> +  "defaultDeleteDescription": "If you proceed, you will lose all your data related to {{name}}. This action is not revocable.",
this could be just deleteDescription

2022-08-12 10:36 UTC, m8vago commented on web/crux-ui/src/elements/dyo-switch.tsx
> +          className={`${
use clsx() instead of `${}`

2022-08-12 10:37 UTC, m8vago commented on web/crux-ui/src/elements/dyo-switch.tsx
> +        className={`${
clsx()

2022-08-12 10:37 UTC, m8vago commented on web/crux-ui/src/models.ts
> +  createdBy: string
we're using createdBy for id's if this is the user's name we could write it like `creator`

2022-08-12 10:38 UTC, m8vago commented on web/crux-ui/src/models.ts
> +export type NotificationItem = Omit<NotificationDetails, 'active'>
is this used in multiple places?

2022-08-12 10:39 UTC, m8vago commented on web/crux-ui/src/pages/api/notifications/hook.ts
> +  res.status(200).json(result)
204

2022-08-12 10:42 UTC, m8vago commented on web/crux-ui/src/pages/notifications/[notificationId].tsx
> +  const [isEditMode, setIsEditMode] = useState<boolean>(false)
[editMode, setEditMode]

2022-08-12 10:54 UTC, m8vago commented on web/crux-ui/src/routes.ts
> +export const notificationApiUrl = (id?: string) => `/api${ROUTE_NOTIFICATIONS}` + (id ? `/${id}` : '')
we need an API_NOTIFICATIONS constant
so we can get rid of the ternary in notificationApiUrl

2022-08-12 10:57 UTC, m8vago commented on web/crux-ui/src/server/crux/notification-service.ts
> +export const toGrpcNotificationType = (type: NotificationType): ProtoNotificationType => {
notificationTypeToGrpc

2022-08-12 10:57 UTC, m8vago commented on web/crux-ui/src/server/crux/notification-service.ts
> +export const toDtoNotificationType = (type: ProtoNotificationType): NotificationType => {
notificationTypeToDto

2022-08-12 10:58 UTC, m8vago commented on web/crux-ui/src/utils.ts
> +export const cursorPointer = (func?: () => void) => func ? 'cursor-pointer' : null
why do we need this?

2022-08-12 11:10 UTC, m8vago commented on web/crux/src/app/notification/notification.service.ts
> +  async getNotificationDetail(request: IdRequest): Promise<NotificationDetailsResponse> {
details*

2022-08-12 11:10 UTC, m8vago commented on web/crux/src/app/notification/notification.service.ts
> +    const notification = await this.prisma.notification.findFirst({
findUnique

2022-08-12 11:11 UTC, m8vago commented on web/crux/src/app/notification/notification.service.ts
> +      var res = await lastValueFrom(this.httpService.post(request.url, { content: 'Its a test!', text: 'Its a test!' }))
`It's a test!` and it should be in a const

2022-08-12 11:14 UTC, m8vago commented on web/crux/src/domain/deployment.ts
> +  accessedBy: string
is this the id of the user?

2022-08-12 11:15 UTC, m8vago commented on web/crux/src/domain/notification-templates.ts
> +export type BaseMessageArg = {
we don't need the arg postfix

2022-08-12 11:15 UTC, m8vago commented on web/crux/src/domain/notification-templates.ts
> +      return null
throw an exception

2022-08-12 11:19 UTC, m8vago commented on web/crux/src/domain/notification-templates.ts
> +  args: MessageArg
it should be message

2022-08-15 10:31 UTC, m8vago commented on protobuf/proto/crux.proto
> +  string createdBy = 2;
id 2 is reserved for audit

use id 100 instead

2022-08-15 10:32 UTC, m8vago commented on web/crux-ui/locales/en/notifications.json
> +  "title-notification": "Notifications - {{name}}",
notificationsName as a key

2022-08-15 10:34 UTC, m8vago commented on web/crux-ui/src/components/notifications/edit-notification-card.tsx
> +  const isEditMode = !!notification.id
no need for is just `editMode`

2022-08-15 10:37 UTC, m8vago commented on web/crux-ui/src/components/notifications/edit-notification-card.tsx
> +    if (!notification.id) {
use the `editing` variable from up there

2022-08-15 11:57 UTC, m8vago approved these changes

2022-08-15 11:59 UTC, merged