feat(crux-ui): yup localization
dyrector-io/dyrectorio pull request #813
Opened 2023-09-07 11:40 UTC by robot9706

- Localize yup schemas using labels.
- Add invalid instance to the toast when deployment validation fails.
- Add red ring around invalid input.
- Refactored config editor error messages a bit (for example environment messages didn't show up)

2023-09-07 13:41 UTC, m8vago requested changes

2023-09-07 13:41 UTC, m8vago commented on web/crux-ui/locales/en/common.json
> +  "validation": {
Please user `error.json`

2023-09-07 13:41 UTC, m8vago commented on web/crux-ui/src/components/projects/versions/images/config/common-config-section.tsx
> +                  message={findErrorFor(fieldErrors, 'name')}
:heart:

2023-09-07 13:41 UTC, m8vago commented on web/crux-ui/src/hooks/use-dyo-formik.ts
> +          validate: (values: any, validationOptions: any) =>
I believe you can get rid of the `new Promise` with declaring this as `async` and a `try catch`.

2023-09-07 13:41 UTC, m8vago commented on web/crux-ui/src/validations/image.ts
> +export type ErrorWithPath = {
I think this should be in `common.ts`

2023-09-07 13:41 UTC, m8vago commented on web/crux-ui/src/validations/yup.ts
> +    return original.replace(/\$\{\s*((\w|:|\.)+)\s*\}/g, (_, key) => yup.printValue(newParams[key]))
Please write some explanations for regexps in a comment.

2023-09-11 13:00 UTC, m8vago requested changes

2023-09-11 19:29 UTC, polaroi8d approved these changes
Wow, good job. LGTM 🦄

2023-09-11 19:29 UTC, polaroi8d commented on web/crux-ui/locales/en/container.json
> +    "pathOverlapsSomePortranges": "{{path}} overlaps some portranges",
"port ranges"

2023-09-13 12:06 UTC, m8vago approved these changes

2023-09-13 12:07 UTC, merged