fix(crux-ui): map versions on new default version
dyrector-io/dyrectorio pull request #83
Opened 2022-08-15 13:39 UTC by balanceee

2022-08-15 14:09 UTC, robot9706 requested changes

2022-08-15 14:09 UTC, robot9706 commented on web/crux-ui/src/pages/products/[productId].tsx
> +import { idText } from 'typescript'
Unused import :)

2022-08-16 06:30 UTC, robot9706 approved these changes
😎

2022-08-16 06:32 UTC, polaroi8d approved these changes
LGTM

2022-08-16 06:32 UTC, merged