feat(web): quality assurance
dyrector-io/dyrectorio pull request #874
Opened 2023-10-31 14:25 UTC by m8vago

- Add posthog for quality assurance purposes.
- Add captures for common elements.
- Add env variables for disable QA.

2023-11-03 10:34 UTC, robot9706 reviewed
Minor comments, haven't tested it yet.

2023-11-03 10:34 UTC, robot9706 commented on web/crux-ui/src/components/projects/versions/deployments/deployment-view-list.tsx
> +          qaLabel: `instance`,
Backtick unnecessary.

2023-11-03 10:34 UTC, robot9706 commented on web/crux-ui/src/elements/dyo-button.tsx
> +    <Link className="inline-block" href={href} onClick={() => sendQAEvent()}>
Simply `onClick={sendQAEvent}` should work too.

2023-11-08 14:23 UTC, gerimate commented
Can you please add this link directing to the docs pls?
- https://docs.dyrector.io/learn-more/software-quality-assurance-sqa

2023-11-09 09:29 UTC, polaroi8d requested changes
In general I think it's not QA, it's Analytics.

2023-11-09 09:29 UTC, polaroi8d commented on web/crux-ui/src/hooks/use-posthog.ts
> +  posthog.init('phc_wc4nEUy7HYW8Elf8G9jiccvl2ZYt8pVts8NVBRMPzHu', {
Is this not a security leak?

2023-11-09 09:47 UTC, robot9706 commented on web/crux-ui/src/elements/dyo-link.tsx
> +      elementType: 'a',
`<a>` as the html anchor.

2023-11-27 12:01 UTC, robot9706 approved these changes

2023-11-28 12:30 UTC, merged