feat: COAL
dyrector-io/dyrectorio pull request #878
Opened 2023-11-03 14:31 UTC by robot9706

- Implement a method to fetch image labels using the V2 registry API
- Add validation based on image labels (COAL)

2023-12-04 07:50 UTC, m8vago requested changes

2023-12-04 07:50 UTC, m8vago commented on web/crux/src/app/image/image.dto.ts
> +  validation: ImageValidation
COAL's ruleset should not bleed into crux's API structure. At this point it should only exist as labels IMHO.

2023-12-04 07:50 UTC, m8vago commented on web/crux/src/domain/image.ts
> +export const parseDyrectorioEnvRules = (labels: Record<string, string>): Record<string, EnvironmentRule> => {
Please write a brief summary with some valid example rules for this function.

2023-12-04 07:50 UTC, m8vago commented on web/crux/src/app/registry/registry-clients/unchecked-api-client.ts
> +    return labelClient.fetchLabels(image, tag)
Unchecked registries have an offline use-case, we simply shouldn't even try to parse COAL rules with them. They are unchecked.

2023-12-05 13:14 UTC, m8vago approved these changes

2023-12-05 14:33 UTC, m8vago commented
Failed to fetch labels with gitlab. Needs further development.

2023-12-15 14:11 UTC, m8vago approved these changes

2023-12-18 16:33 UTC, polaroi8d approved these changes

2023-12-18 16:33 UTC, merged