feat: container expected state
dyrector-io/dyrectorio pull request #891
Opened 2023-12-07 14:23 UTC by robot9706

2023-12-21 15:21 UTC, m8vago requested changes
Let's move this to the docker config section.
Also please add a configuration option for timeout.

2023-12-23 08:59 UTC, polaroi8d commented
Please fill out the pull request description.

2024-01-31 13:21 UTC, nandor-magyar approved these changes
It looks good, apart from that single unused variable.

2024-01-31 13:21 UTC, nandor-magyar commented on golang/pkg/crane/k8s/deploy_facade.go
> +const PodStateTimeoutSeconds = 120
It seems unused, is it?

2024-01-31 14:35 UTC, m8vago approved these changes

2024-01-31 15:05 UTC, merged