fix(web): v2 manifest list & yup translate error
dyrector-io/dyrectorio pull request #896
Opened 2023-12-21 13:04 UTC by robot9706

- Fix label fetching crashing when the manifest is a list.
- Fix yup error translate when inner errors are empty.

2023-12-21 15:19 UTC, m8vago requested changes

2023-12-21 15:19 UTC, m8vago commented on web/crux/src/app/registry/registry-clients/v2-labels.ts
> +            return {}
let's collect them recursively?

2023-12-23 08:58 UTC, polaroi8d approved these changes
Okey for me.

2024-01-10 10:29 UTC, m8vago approved these changes

2024-01-10 13:29 UTC, merged