feat(web): add image push and pull to notifications
dyrector-io/dyrectorio pull request #897
Opened 2023-12-21 20:51 UTC by m8vago

Add new notification types:
- Image push
- Image pull

2024-01-11 08:55 UTC, polaroi8d requested changes

2024-01-11 08:55 UTC, polaroi8d commented on web/crux/src/app/registry/guards/registry.auth.validation.guard.ts
> +      .get(`http://${req.url}/v2/`, {
Is this a real change?

2024-01-11 08:55 UTC, polaroi8d commented on web/crux/src/app/registry/registry-clients/v2-api-client.ts
> +    const fullUrl = `http://${this.url}/v2${endpoint}`
Same question here.

2024-01-11 13:26 UTC, m8vago commented on web/crux/src/app/registry/registry-clients/v2-api-client.ts
> +    const fullUrl = `http://${this.url}/v2${endpoint}`
Nope. Nice catch!

2024-01-11 18:15 UTC, polaroi8d approved these changes
Okey for me, pleas @robot9706 if you have time check it please.

2024-01-12 07:48 UTC, robot9706 reviewed
Sesms fine to me, but couldn't test it. One comment on the migration though.

2024-01-12 07:48 UTC, robot9706 commented on web/crux/prisma/migrations/20231019133412_deploy_log/migration.sql
> -UPDATE "DeploymentEvent"
Why this older migrations is modified?

2024-01-12 15:03 UTC, robot9706 approved these changes

2024-01-15 08:49 UTC, merged