feat(crux-ui): show versions on product/version edit
dyrector-io/dyrectorio pull request #90
Opened 2022-08-17 10:32 UTC by balanceee

2022-08-17 13:23 UTC, polaroi8d approved these changes
LGTM

2022-08-17 14:26 UTC, m8vago commented on web/crux-ui/src/components/products/product-versions-section.tsx
> +  return props.versions ? (
we shouldn't bury deep down null checks.
please set versions to non-nullable, and simply check for null at the place of usage

2022-08-17 14:27 UTC, m8vago commented on web/crux-ui/src/components/products/versions/version-card.tsx
> +  readonly?: boolean
use `disabled` please

2022-08-17 14:36 UTC, robot9706 requested changes

2022-08-17 14:36 UTC, robot9706 commented on web/crux-ui/src/components/products/edit-product-card.tsx
> +      <ProductVersionsSection productId={product.id} versions={props.versions} readonly />
In my opinion `ProductVersionsSection` shouldn't handle the undefined case. In `ProductVersionsSection` `versions` should be mandatory and `EditProductCard` should hande the undefined case (for example `props.version ?? []`).

This way `ProductVersionsSection` doesn't need an empty fragment.

2022-08-18 08:27 UTC, robot9706 approved these changes
😎

2022-08-18 10:12 UTC, m8vago approved these changes

2022-08-18 10:12 UTC, m8vago commented
Nice work!

2022-08-18 10:13 UTC, merged