Add dependency check targets to Makefile
dyrector-io/dyrectorio pull request #901
Opened 2024-01-16 06:02 UTC by Parvezkhan0

Fixes #628

2024-01-17 06:59 UTC, polaroi8d requested changes
The direction is good, but we just need simple functions to return a message about which dependencies are missing. Regarding your solution, there is no dependency check in Node.js. It would be nice if you could implement a general check that calls all the dependencies, so users don't need to run each command one by one.

2024-01-17 06:59 UTC, polaroi8d commented on Makefile
> +protogen:| proto-agent proto-crux
Missing new line end of the file.

2024-01-17 06:59 UTC, polaroi8d commented on Makefile
> +	@echo "All dependencies are up to date."
This is not checking the dependencies, this is just a simple echo. Please remove it, implement it or add a TODO comment to implement in later.

2024-01-17 06:59 UTC, polaroi8d commented on Makefile
> +	@echo "Checking Node.js dependencies..."
This function does not check the dependencies.

2024-01-17 09:40 UTC, Parvezkhan0 commented
@polaroi8d, I incorporated the changes you advised. Please review my PR again.

2024-01-17 10:11 UTC, polaroi8d requested changes
There are still a bunch of errors and problems. Please take your time to think over the task and find the best possible solution.

...And the PR title is not valid. Please check the CONTRIBUTING.md for how we format PRs; you missed specifying the scope and type of the contribution.

2024-01-17 10:11 UTC, polaroi8d commented on Makefile
> +	@npm install 2>&1 | grep "npm ERR!" && (echo "Node.js dependencies are missing" && exit 1) || echo "Node.js dependencies are up to date."
If I have an outdated npm version, it will still indicate that my Node.js version is up-to-date, but this is not true at that moment."

2024-01-17 10:11 UTC, polaroi8d commented on Makefile
> +	@go list -f '{{if not .Indirect}}{{.}}{{end}}' ./... | xargs go list -f '{{if not .Standard}}{{.ImportPath}}{{end}}' | xargs go get -u 2>&1 | grep "go: "
Got the following error message when try out this command: 

```
Checking Golang dependencies...
template: main:1:9: executing "main" at <.Indirect>: can't evaluate field Indirect in type *load.PackagePublic
make: *** [check-golang-dependencies] Error 1
```

2024-01-17 10:11 UTC, polaroi8d commented on Makefile
> +	@npm install 2>&1 | grep "npm ERR!" && (echo "Node.js dependencies are missing" && exit 1) || echo "Node.js dependencies are up to date."
Got the following error: 

```
Checking Node.js dependencies...
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /xxx/.../package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/xxx/.../package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! A complete log of this run can be found in: /xxx/.../.npm/_logs/2024-01-17T10_08_11_168Z-debug-0.log
Node.js dependencies are missing
Node.js dependencies are up to date.
```

2024-01-23 08:54 UTC, polaroi8d commented
The PR title is still invalid, eg. you can use: `feat: add dependency check to Makefile`

2024-01-31 05:34 UTC, polaroi8d commented
Any update on this @Parvezkhan0? We have to close due to the inactivity.

2024-02-01 10:50 UTC, polaroi8d commented
Close the PR due the inactivity. Feel free to reopen.

2024-02-01 10:50 UTC, closed without merging