fix(web): breadcrumb navigations on list pages
dyrector-io/dyrectorio pull request #928
Opened 2024-02-27 16:22 UTC by m8vago

Fix: Breadcrumb navigation on list pages while creating a new item.

2024-03-13 10:26 UTC, nandor-magyar requested changes

2024-03-13 10:26 UTC, nandor-magyar commented on web/crux-ui/Dockerfile
> +CMD [ "node", "server.js" ]
Using the ENTRYPOINT directive is preferable over CMD, though technically there is no much difference how it is executed.

2024-03-13 10:53 UTC, nandor-magyar commented on web/crux-ui/Dockerfile
> +CMD [ "node", "server.js" ]
We had a discussion that we need the entrypoint from the original image.
```sh
#!/bin/sh
set -e

# Run command with node if the first argument contains a "-" or is not a system command. The last
# part inside the "{}" is a workaround for the following bug in ash/dash:
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=874264
if [ "${1#-}" != "${1}" ] || [ -z "$(command -v "${1}")" ] || { [ -f "${1}" ] && ! [ -x "${1}" ]; }; then
  set -- node "$@"
fi

exec "$@"
```

This is the content, so maybe just providing `server.js` would be enough then, to make it more apparent that there is also an entrypoint defined and it is in-use.

2024-03-13 14:23 UTC, nandor-magyar approved these changes

2024-03-18 08:43 UTC, polaroi8d approved these changes
Didn't tested in local, code looks okey for me.

2024-03-19 14:26 UTC, robot9706 commented on web/crux-ui/e2e/utils/node-helper.ts
> +  page.addListener('framenavigated', frame => console.info('PW navigated', frame.url()))
`console.info` :)

2024-03-19 15:05 UTC, robot9706 approved these changes

2024-03-20 09:55 UTC, merged