Fix/text overflow
dyrector-io/dyrectorio pull request #97
Opened 2022-08-19 08:52 UTC by bvektor

Implemented an ExpandableText component to use where its possible for text to overflow and cause glitches.

2022-08-19 09:14 UTC, robot9706 requested changes

2022-08-19 09:14 UTC, robot9706 commented on web/crux-ui/src/components/nodes/edit-node-card.tsx
> +      <DyoWrap className={clsx(props.className, 'flex flex-row ')}>
Extra space after "flex-row" ?

2022-08-19 11:16 UTC, polaroi8d requested changes
Talked in-person some minor issues.

2022-08-19 11:28 UTC, m8vago requested changes

2022-08-19 11:28 UTC, m8vago commented on web/crux-ui/src/components/products/product-card.tsx
> +          <div className="text-md text-bright mt-4 line-clamp-2 break-words">{product.description}</div>
why div?

2022-08-19 11:28 UTC, m8vago commented on web/crux-ui/src/components/products/product-details-card.tsx
> +          <div className="flex flex-col flex-grow w-px">
w-px ??

2022-08-19 11:28 UTC, m8vago commented on web/crux-ui/src/components/products/product-details-card.tsx
> +          <div className="flex flex-col flex-grow w-px">
layout="fixed"  to the image so we don't need w-px

2022-08-19 11:28 UTC, m8vago commented on web/crux-ui/src/components/products/versions/version-details-card.tsx
> +            className="text-md text-slate-500"
text-light from all slate-500

2022-08-22 13:12 UTC, m8vago approved these changes

2022-08-22 14:22 UTC, robot9706 approved these changes
🙌

2022-08-23 08:12 UTC, polaroi8d approved these changes
LGTM

2022-08-23 08:20 UTC, merged